workflows:
  ios-workflow:
    name: iOS workflow
    environment:
      groups:
        # Add the group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
          - app_store_credentials # <-- (Includes APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY)
            # APP_STORE_CONNECT_ISSUER_ID <-- Put your App Store Connect Issuer Id here 
            # APP_STORE_CONNECT_KEY_IDENTIFIER <-- Put your App Store Connect Key Identifier here 
            # APP_STORE_CONNECT_PRIVATE_KEY <-- Put your App Store Connect Private Key here
            # See the following link for more details - https://docs.codemagic.io/code-signing-yaml/signing-ios/
            # https://appstoreconnect.apple.com/access/api
          - certificate_credentials # <-- (Includes CERTIFICATE_PRIVATE_KEY) 
            #b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcnNhAAAAAwEAAQAAAQEA3m8wzEU9nJrVWrKETRa0YoLrq4g1Tcf1H13J0LfUcPvqVOxw+wwqBQokhTPkB8sENuHX8bK5vvhWrC7uCc9lCrXhynE0NQCy+9eZQMB78oDpt/JFTUBGqJ9lAU40bqU70balzI0FB6AZqS+h4G7mxxRNrP0lPNXr0sFowEx2Lquv2vlfvotKdH6Iu4OHB9ZqHGKleSCTOFLPuT2bvEJL5DMMNWj3xhrePxe9hpfIxfFHY7dbz/hJ6X8pcOea/QCo0+nCFnXdItNHNauDbckq4K/7EX4fXNpbUgFZ7w6GwfyeVvDSPszZELqGt2cIsYm4728J9WZQc5yFvmD761tP7QAAA9iYpfChmKXwoQAAAAdzc2gtcnNhAAABAQDebzDMRT2cmtVasoRNFrRiguuriDVNx/UfXcnQt9Rw++pU7HD7DCoFCiSFM+QHywQ24dfxsrm++FasLu4Jz2UKteHKcTQ1ALL715lAwHvygOm38kVNQEaon2UBTjRupTvRtqXMjQUHoBmpL6HgbubHFE2s/SU81evSwWjATHYuq6/a+V++i0p0foi7g4cH1mocYqV5IJM4Us+5PZu8QkvkMww1aPfGGt4/F72Gl8jF8Udjt1vP+Enpfylw55r9AKjT6cIWdd0i00c1q4NtySrgr/sRfh9c2ltSAVnvDobB/J5W8NI+zNkQuoa3Zwixibjvbwn1ZlBznIW+YPvrW0/tAAAAAwEAAQAAAQEA1CMJUBfNLdlBF7HfmcHIoZco+jv6Ukcc0SBahFN+KY8oKnwhOFyeipXkxKD7ni8RwuHbWGjS233u82ICpZqFTBSw1ajnWJFlIei6AVZSH7KwtD07uPRPLyxtYTRbrxapGVXvhEkN/frD3mZOJUS/ligX+J6pb/65XRQWOifyIojV2NNgaGr2f3Rli7pgjfrZ1skCAlnvgQ+ZGKDMvIyLk7dcKpbb4GFZO/dAjdchaAy6zDB+L01YSn8LenYYwCJtHJTX8pnfOsqBbcmBQQq0SeY0oPN57XEuHxjQLEUq3hj92dVgw6H8vkPPaPIIg7AQRrpWx6nY1h8Gqg7r5GCRhQAAAIEAmd4+SxZKaf0bCIU+HDGxWlYoUM3COooHsRylqDMW+0vAUA6zvIIznbC4Rbtm1ljrGkErwq0Snl5Zkh92vbrClX2AY0VqZaQLkdWY1R/YNZmIhAjA0oTnCERPm9oInJsUYN1d7qpZS4bTkJiJn5ouYYwe5TIqMVjhDqj7qjxOUAsAAACBAPYgxmPQ3WdXiNGFd8W0B6U8Rl9Ist5lukQYExnNxj9ZmzdU0pGECfSDsYePQrIhZdPr30CLqANliIxKSx3h4d3qHdkzqZs8m8Pmz9khX7PVojHEBlYbg3JowRIPseeoZt7qiSiPHSPcbDpM1iL8OE9MoJlkSDlgQaamey/KGUi/AAAAgQDnWyFrmv7pIuc8rB/IUlCuM9qXMtdYjF1eXav2TNSK2tnCEc+N8gdv2Qrt+lkiU8ysWdp/NqbjEODJlYkbQqXtthAHaP5Xct0dEUDcLdU3T1yUSS/3fCJiBunFrcn1WSkcYe1LTn+AtiLu96kX6nAvPz47iubRvv6ITplKxVvGUwAAAB9WZWxhbkBEZWxpcGhzLU1hY0Jvb2stUHJvLmxvY2FsAQI=
                - other
      vars:      
        BUNDLE_ID: "io.codemagic.ioniccordova" # <-- Put your Bundle Id here 
      xcode: 12.4
      node: 12
      npm: 6
    cache:
      cache_paths:
        - $FCI_BUILD_DIR/node_modules
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm ci
          cvm install 9.0.0
          cvm use 9.0.0
          npm install -g ionic
          ionic info   
      - name: Setup iOS
        script: |
          ionic cordova platform remove ios --nosave
          ionic cordova platform add ios --confirm --no-interactive --noresources --save  
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
      - name: Add certificates to keychain
        script: |
          keychain add-certificates         
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build iOS
        script: |
          package_type=$(defaults read ~/export_options.plist method)
          identity=$(defaults read ~/export_options.plist signingCertificate)
          team=$(defaults read ~/export_options.plist teamID)
          profile=$(find '/Users/builder/Library/MobileDevice/Provisioning Profiles' -name "*.mobileprovision")
          profile_uuid=$(grep UUID -A1 -a "$profile" | grep -io "[-A-F0-9]\{36\}")
        
          cat <<EOF > build.json
              {
                "ios": {
                  "release": {
                    "codeSignIdentity": "$identity",
                    "developmentTeam": "$team",
                    "packageType": "$package_type",
                    "provisioningProfile": "$profile_uuid"
                  }
                }
              }
          EOF
          ionic cordova build ios --release --device --buildConfig='build.json' 
    artifacts:
      - /Users/builder/clone/platforms/ios/build/device/*.ipa
      - /tmp/xcodebuild_logs/*.log           
    publishing:
      # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true     # To not receive a notification when a build succeeds
          failure: false    # To not receive a notification when a build fails
      slack: 
        # See the following link about how to connect your Slack account - https://docs.codemagic.io/publishing-yaml/distribution/#slack
        channel: '#channel-name'
        notify_on_build_start: true   # To receive a notification when a build starts
        notify:
          success: true               # To not receive a notification when a build succeeds
          failure: false              # To not receive a notification when a build fails
      app_store_connect:                 
         api_key: $APP_STORE_CONNECT_PRIVATE_KEY         # Contents of the API key, can also reference environment variable such as $APP_STORE_CONNECT_PRIVATE_KEY
         key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER       # Alphanumeric value that identifies the API key, can also reference environment variable such as $APP_STORE_CONNECT_KEY_IDENTIFIER
         issuer_id: $APP_STORE_CONNECT_ISSUER_ID         # Alphanumeric value that identifies who created the API key, can also reference environment variable such as $APP_STORE_CONNECT_ISSUER_ID
         submit_to_testflight: false                     # Optional boolean, defaults to false. Whether or not to submit the uploaded build to TestFlight beta review. Required for distributing to beta groups. Note: This action is performed during post-processing.
         #  beta_groups:                                 # Specify the names of beta tester groups that will get access to the build once it has passed beta review. 
         #     - group name 1
         #     - group name 2     
  android-workflow:
    name: Android workflow
    environment:
      groups:
        # Add the group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
        - keystore_credentials # <-- (Includes KEYSTORE, KEYSTORE_PASSWORD, KEY_ALIAS_PASSWORD, KEY_ALIAS, KEYSTORE_PATH)
          # KEYSTORE <-- Put your keystore file here
          # KEYSTORE_PASSWORD <-- Put your keystore password here
          # KEY_ALIAS_PASSWORD <-- Put your keystore alias password here
          # KEY_ALIAS <-- Put your keystore alias username here
          # KEYSTORE_PATH: '/tmp/keystore.keystore'
        - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS - Put your google-services.json here)
        - other
      xcode: 12.4
      node: 12
      npm: 6        
    cache:
      cache_paths:
        - $FCI_BUILD_DIR/node_modules
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm ci
          cvm install 9.0.0
          cvm use 9.0.0
          npm install -g ionic
          ionic info        
      - name: Add Android platform
        script: |
          set -x
          ionic cordova platform remove android --nosave
          ionic cordova platform add android --confirm --no-interactive --noresources
      - name: Build Android
        script: |    
          set -x
          set -e
          ionic cordova build android --release --no-interactive --prod --device
          echo $KEYSTORE | base64 --decode > $KEYSTORE_PATH
          UNSIGNED_APK_PATH=$(find platforms/android/app/build/outputs -name "*.apk" | head -1)
          jarsigner -sigalg SHA1withRSA -digestalg SHA1 -keystore "${KEYSTORE_PATH}" -storepass "${KEYSTORE_PASSWORD}" -keypass "${KEY_ALIAS_PASSWORD}" "${UNSIGNED_APK_PATH}" "${KEY_ALIAS}"
          mv $UNSIGNED_APK_PATH $(echo $UNSIGNED_APK_PATH | sed 's/-unsigned//')
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
      - platforms/android/app/build/outputs/**/mapping.txt
    publishing:
        # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
        email:
            recipients:
                - user_1@example.com
                - user_2@example.com
            notify:
              success: true     # To not receive a notification when a build succeeds
              failure: false    # To not receive a notification when a build fails
        slack: 
          # See the following link about how to connect your Slack account - https://docs.codemagic.io/publishing-yaml/distribution/#slack
          channel: '#channel-name'
          notify_on_build_start: true   # To receive a notification when a build starts
          notify:
            success: true               # To not receive a notification when a build succeeds
            failure: false              # To not receive a notification when a build fails
        google_play:
          # See the following link for information regarding publishing to Google Play - https://docs.codemagic.io/publishing-yaml/distribution/#google-play
          credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
          track: alpha      
